site_name: Tile
repo_url: https://github.com/tile-dev/tile
repo_name: tile-dev/tile
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    primary: indigo
  logo: /assets/tile.svg
  font: 
    text: Inter
  custom_dir: docs/overrides/
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
    - Home: index.md
    - Community:
        - 'community.md'
    - About:
      - 'What is Tile?' : 'about/what.md'
      - 'Mission' : 'about/mission.md'
      - 'Roadmap' : 'about/roadmap.md'
      - 'Use-cases': 'about/usecases.md'
      - 'FAQ': 'about/faq.md'
      - 'Comparisons' : 'about/comparisons.md'
    - Docs:
      - Getting Started : 'docs/getting-started.md'
copyright: Copyright &copy; 2022 Tile by Datapane. All rights reserved.